"""Visualization module exports."""

from src.visualization.plots import (
    plot_actual_vs_predicted,
    plot_boxplots,
    plot_categorical_distributions,
    plot_class_distribution,
    plot_class_distribution_from_result,
    plot_classifier_comparison,
    plot_confusion_matrix,
    plot_confusion_matrix_comparison,
    plot_correlation_matrix,
    plot_correlation_with_target,
    plot_driver_behavior_distribution,
    plot_feature_by_target,
    plot_feature_distributions,
    plot_feature_importance,
    plot_learning_curves,
    plot_model_comparison,
    plot_model_comparison_detailed,
    plot_outlier_summary,
    plot_prediction_intervals,
    plot_regressor_comparison,
    plot_residual_analysis,
    plot_residuals,
    plot_target_distribution_regression,
    plot_target_vs_categorical_features,
    plot_target_vs_numerical_features,
    plot_training_history,
    setup_style,
)

__all__ = [
    "setup_style",
    # Class distribution
    "plot_class_distribution",
    "plot_class_distribution_from_result",
    "plot_driver_behavior_distribution",
    # Feature analysis
    "plot_feature_by_target",
    "plot_outlier_summary",
    "plot_correlation_with_target",
    "plot_target_distribution_regression",
    "plot_feature_distributions",
    "plot_correlation_matrix",
    "plot_boxplots",
    "plot_categorical_distributions",
    # Model evaluation - Classification
    "plot_confusion_matrix",
    "plot_confusion_matrix_comparison",
    "plot_classifier_comparison",
    "plot_training_history",
    "plot_feature_importance",
    # Model evaluation - Regression
    "plot_residuals",
    "plot_actual_vs_predicted",
    "plot_model_comparison",
    "plot_learning_curves",
    "plot_regressor_comparison",
    "plot_residual_analysis",
    "plot_prediction_intervals",
    "plot_model_comparison_detailed",
    # Target vs Features
    "plot_target_vs_numerical_features",
    "plot_target_vs_categorical_features",
]
